title: Some thing goes by
email: wangyuhengs@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is my site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: c1tas
github_username:  c1tas

permalink:   /:categories/:title/


remoteimg: https://django.c1tas.com/pic

# Build settings
markdown: kramdown
theme: hackme
gems:
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - hackme.gemspec
  - README.md

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

highlighter: rouge